#
# Cloudbuild config for main branch
#

# [START cloudbuild]
steps:

  - id: chmod
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        mkdir -p /workspace/output && chmod -R 777 /workspace/output
    waitFor: ['-']

  - id: "build-django-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
        "--destination", "asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}",
        "--destination", "asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:latest",
        "--cache=true",
        "--cache-ttl=336h0m0s", # 2 weeks (default)
        "--context=django-app",
        "--target=build-image"
    ]
    waitFor: ['-']

  - id: "build-selenium-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:${COMMIT_SHA}",
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:latest",
      "--cache=true",
      "--cache-ttl=336h0m0s", # 2 weeks (default)
      "--context=selenium-tests",
      "--build-arg", "BASE_IMAGE=asia.gcr.io/${PROJECT_ID}/selenium-runner:latest"
    ]
    waitFor: ['-']

  - id: "build-localstripe-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:${COMMIT_SHA}",
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:latest",
      "--cache=true",
      "--cache-ttl=336h0m0s", # 2 weeks (default)
      "--context=localstripe",
      "--build-arg", "BASE_IMAGE=asia.gcr.io/${PROJECT_ID}/localstripe:latest"
    ]
    waitFor: ['-']

  # Pull the images. It seems more efficient to do this separately. At least, this means
  # we can start pulling the image for each, prior to both builds completing
  - id: docker-pull-django
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-django-image]

  - id: docker-pull-selenium
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-selenium-image]

  - id: docker-pull-localstripe
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-localstripe-image]

  # Start containers to run automated tests
  - id: start-docker-compose
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: ['compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'up', '-d']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=${COMMIT_SHA}'
      - 'IMAGE_PREFIX=asia.gcr.io/${PROJECT_ID}/'
    waitFor: [docker-pull-django, docker-pull-selenium, docker-pull-localstripe]

  # Run selenium tests
  - id: selenium-tests
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
      'compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'run', 'selenium_tests', 'run_tests', '--continue-on-failure', '--ignore-errors'
    ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=${COMMIT_SHA}'
      - 'IMAGE_PREFIX=asia.gcr.io/${PROJECT_ID}/'
    waitFor: [start-docker-compose]

  - id: upload-selenium-output
    name: "gcr.io/cloud-builders/gsutil"
    args: [
        'cp', '-Z',
        '/workspace/output/test_output.html',
        'gs://${PROJECT_ID}_cloudbuild/output/main/test_output.html'
    ]
    waitFor: [selenium-tests]

  - id: print-selenium-url
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        echo "Images uploaded to https://storage.cloud.google.com/${PROJECT_ID}_cloudbuild/output/main/test_output.html"
    waitFor: [selenium-tests]
  
  # Check that all tests passed successfully
  - id: check-test-status
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
      'compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'run', 'selenium_tests', 'check_test_status'
    ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=${COMMIT_SHA}'
      - 'IMAGE_PREFIX=asia.gcr.io/${PROJECT_ID}/'
    waitFor: [upload-selenium-output, print-selenium-url]

    # Bring down the docker-compose stack
  - id: docker-compose-down
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: ['compose', '-f', 'docker/docker-compose.yml', 'down', '--remove-orphans']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    waitFor: [check-test-status]

  ## Deploy to staging #######################

  # Update the google cloud run job to use the latest image
  - id: backend-job-update
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['beta', 'run', 'jobs', 'update', 'newstream-init', '--project', '${_TARGET_PROJECT_ID}', '--region', 'asia-southeast1', '--image', 'asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${_COMMIT_TAG}']
    waitFor: [check-test-status]

  # Execution the cloud run job to run migrations, etc
  - id: backend-migrate
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['beta', 'run', 'jobs', 'execute', 'newstream-init', '--project', '${_TARGET_PROJECT_ID}', '--region', 'asia-southeast1', '--wait']
    waitFor: [backend-job-update]

  # Deploy the backend update
  - id: deploy-backend-cloud-run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'backend', '--project', '${_TARGET_PROJECT_ID}', '--platform', 'managed', '--image', 'asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${_COMMIT_TAG}', '--region', 'asia-southeast1']
    waitFor: [backend-migrate]

substitutions:
  _BACKEND_SERVICE_NAME: newstream
  _SELENIUM_SERVICE_NAME: newstream-tests
  _LOCALSTRIPE_SERVICE_NAME: localstripe

# [END cloudbuild]]
