#
# Cloudbuild config for main branch
#

# [START cloudbuild]
steps:

  - id: chmod
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        mkdir -p /workspace/output && chmod -R 777 /workspace/output
    waitFor: ['-']

  - id: "build-django-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
        "--destination", "asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}",
        "--destination", "asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:latest",
        "--cache=true",
        "--cache-ttl=336h0m0s", # 2 weeks (default)
        "--context=django-app",
        "--target=build-image"
    ]
    waitFor: ['-']

  - id: "build-selenium-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:${COMMIT_SHA}",
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:latest",
      "--cache=true",
      "--cache-ttl=336h0m0s", # 2 weeks (default)
      "--context=selenium-tests",
      "--build-arg", "BASE_IMAGE=asia.gcr.io/${PROJECT_ID}/selenium-runner:latest"
    ]
    waitFor: ['-']

  - id: "build-localstripe-image"
    name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:${COMMIT_SHA}",
      "--destination", "asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:latest",
      "--cache=true",
      "--cache-ttl=336h0m0s", # 2 weeks (default)
      "--context=localstripe",
      "--build-arg", "BASE_IMAGE=asia.gcr.io/${PROJECT_ID}/localstripe:latest"
    ]
    waitFor: ['-']

  # Pull the images. It seems more efficient to do this separately. At least, this means
  # we can start pulling the image for each, prior to both builds completing
  - id: docker-pull-django
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-django-image]

  - id: docker-pull-selenium
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_SELENIUM_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-selenium-image]

  - id: docker-pull-localstripe
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia.gcr.io/${PROJECT_ID}/${_LOCALSTRIPE_SERVICE_NAME}:${COMMIT_SHA}',
    ]
    waitFor: [build-localstripe-image]

  # Start containers to run automated tests
  - id: start-docker-compose
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: ['compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'up', '-d']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=${COMMIT_SHA}'
      - 'IMAGE_PREFIX=asia.gcr.io/${PROJECT_ID}/'
      - 'BACKEND_IMAGE_NAME=${_BACKEND_SERVICE_NAME}'
      - 'SELENIUM_IMAGE_NAME=${_SELENIUM_SERVICE_NAME}'
      - 'LOCALSTRIPE_IMAGE_NAME=${_LOCALSTRIPE_SERVICE_NAME}'
    waitFor: [docker-pull-django, docker-pull-selenium, docker-pull-localstripe]

  # Run selenium tests
  - id: selenium-tests
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
      'compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'run', 'selenium_tests', 'run_tests',
    ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=${COMMIT_SHA}'
      - 'IMAGE_PREFIX=asia.gcr.io/${PROJECT_ID}/'
      - 'BACKEND_IMAGE_NAME=${_BACKEND_SERVICE_NAME}'
      - 'SELENIUM_IMAGE_NAME=${_SELENIUM_SERVICE_NAME}'
      - 'LOCALSTRIPE_IMAGE_NAME=${_LOCALSTRIPE_SERVICE_NAME}'
    waitFor: [start-docker-compose]

    # Bring down the docker-compose stack
  - id: docker-compose-down
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: ['compose', '-f', 'docker/docker-compose.yml', 'down', '--remove-orphans']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    waitFor: [selenium-tests]

substitutions:
  _BACKEND_SERVICE_NAME: newstream
  _SELENIUM_SERVICE_NAME: newstream-tests
  _LOCALSTRIPE_SERVICE_NAME: localstripe

# [END cloudbuild]]
