#
# Cloudbuild config for main branch
#

# [START cloudbuild]
steps:

  # Create the output directory for selenium to write to
  - id: chmod
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        mkdir -p /workspace/output && chmod -R 777 /workspace/output
    waitFor: ['-']

  - id: "build-django-image"
    name: "gcr.io/kaniko-project/executor:v1.10.0"
    args: [
        "--destination", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_BACKEND_SERVICE_NAME}:pr-${_PR_NUMBER}",
        "--destination", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_BACKEND_SERVICE_NAME}:${COMMIT_SHA}",
        "--cache=true",
        "--cache-ttl=336h0m0s", # 2 weeks (default)
        "--context=django-app",
        "--target=build-image",
        "--build-arg=APP_VERSION=${SHORT_SHA}"
    ]
    waitFor: ['-']

  - id: "build-selenium-image"
    name: "gcr.io/kaniko-project/executor:v1.10.0"
    args: [
      "--destination", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_SELENIUM_SERVICE_NAME}:pr-${_PR_NUMBER}",
      "--cache=true",
      "--cache-ttl=336h0m0s", # 2 weeks (default)
      "--context=selenium-tests",
      "--build-arg", "BASE_IMAGE=asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/selenium-runner:latest"
    ]
    waitFor: ['-']

  # Pull the images. It seems more efficient to do this separately. At least, this means
  # we can start pulling the image for each, prior to both builds completing
  - id: docker-pull-django
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_BACKEND_SERVICE_NAME}:pr-${_PR_NUMBER}',
    ]
    waitFor: [build-django-image]

  - id: docker-pull-selenium
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_SELENIUM_SERVICE_NAME}:pr-${_PR_NUMBER}',
    ]
    waitFor: [build-selenium-image]

  - id: docker-pull-localstripe
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_LOCALSTRIPE_SERVICE_NAME}:latest',
    ]
    waitFor: ['-']

  - id: docker-pull-localpaypal
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
        'pull', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_LOCALPAYPAL_SERVICE_NAME}:latest',
    ]
    waitFor: ['-']

  # Run unit tests
  - id: unit-tests-django
    name: "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/${_BACKEND_SERVICE_NAME}:pr-${_PR_NUMBER}"
    args: ["run_tests"]
    waitFor: [docker-pull-django, docker-pull-selenium, docker-pull-localstripe]

  # Run selenium tests
  - id: selenium-tests
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
      'compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'run', 'selenium_tests', 'run_tests', '--continue-on-failure', '--ignore-errors'
    ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=pr-${_PR_NUMBER}'
      - 'IMAGE_PREFIX=asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/'
    waitFor: [docker-pull-django, docker-pull-selenium, docker-pull-localstripe, docker-pull-localpaypal]

  - id: upload-selenium-output
    name: "gcr.io/cloud-builders/gsutil"
    args: [
        'cp', '-Z',
        '/workspace/output/test_output.html',
        'gs://${PROJECT_ID}_cloudbuild/output/pr-${_PR_NUMBER}/test_output.html'
    ]
    waitFor: [selenium-tests]

  - id: print-selenium-url
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        echo "Images uploaded to https://storage.cloud.google.com/${PROJECT_ID}_cloudbuild/output/pr-${_PR_NUMBER}/test_output.html"
    waitFor: [selenium-tests]

  # Check that all tests passed successfully
  - id: check-test-status
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: [
      'compose', '-f', 'docker/docker-compose.yml', '-f', 'docker/docker-compose-gcp.yml', 'run', 'selenium_tests', 'check_test_status'
    ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_TAG=pr-${_PR_NUMBER}'
      - 'IMAGE_PREFIX=asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker-images/'
    waitFor: [upload-selenium-output, print-selenium-url]

  # Bring down the docker-compose stack
  - id: docker-compose-down
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    args: ['compose', '-f', 'docker/docker-compose.yml', 'down', '--remove-orphans']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    waitFor: [check-test-status]

substitutions:
  _BACKEND_SERVICE_NAME: newstream
  _SELENIUM_SERVICE_NAME: newstream-tests
  _LOCALSTRIPE_SERVICE_NAME: localstripe
  _LOCALPAYPAL_SERVICE_NAME: localpaypal

# We use a higher spec machine for performance, particularly for the selenium tests
options:
  machineType: 'N1_HIGHCPU_8'

# [END cloudbuild]]
