# Generated by Django 3.0.8 on 2020-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
