# Generated by Django 3.0.8 on 2020-08-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usermeta',
            options={'ordering': ['-id'], 'verbose_name': 'User Meta', 'verbose_name_plural': 'User Metas'},
        ),
    ]
