# Generated by Django 3.0.8 on 2020-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hant', 'Traditional Chinese'), ('ms', 'Malay'), ('ind', 'Indonesian'), ('tl', 'Tagalog')], max_length=10),
        ),
    ]
