# Generated by Django 3.0.8 on 2021-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0004_auto_20210104_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionupdateslog',
            name='action_notes',
            field=models.TextField(blank=True),
        ),
    ]
