# Generated by Django 3.0.8 on 2021-03-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0007_auto_20210306_1823'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
