#!/bin/bash

while true; do
    read -p "Do you wish to delete all users, donations, email campaigns from the newstream database?" yn
    case $yn in
        [Yy]* ) sudo mysql -u root -p -D newstream -e "SET FOREIGN_KEY_CHECKS=0;delete from donations_donation;delete from donations_donationmeta;delete from donations_donationpaymentmeta;delete from donations_subscription;delete from donations_subscriptionpaymentmeta;delete from email_campaigns_campaign;delete from email_campaigns_campaign_recipients;delete from email_campaigns_emailtemplate;delete from email_campaigns_targetgroup;delete from email_campaigns_targetgroup_users;delete from socialaccount_socialaccount;delete from socialaccount_socialtoken;delete from account_emailaddress;delete from newstream_user_user where id <> 1;delete from newstream_user_usersubscriptionupdateslog;"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done