#!/bin/bash

ismigrate='false'
isxgulp='false'

print_usage() {
    printf "%s\n" "Usage: ./deploy [-h] [-g] [-m]" "zero flags = rsync and restart" "-h is for help" "-g is for executing gulp first before deploy" "-m is for migration at remote django before restarting gunicorn"
}

while getopts 'mgh' flag; do
    case "${flag}" in
        m) ismigrate='true' ;;
        g) isxgulp='true' ;;
        h) print_usage
           exit 1 ;;
    esac
done

xgulp="npx gulp"
rsync="rsync -av --exclude '.git' --exclude 'node_modules' ./ diff-1:/srv/www/newstream/"
ssh='ssh diff-1'
source='cd /srv/www/newstream && source ~/.profile && source venv/bin/activate && export LC_ALL="en_US.UTF-8"'
migrate='python manage.py makemigrations && python manage.py migrate'
startg='sudo supervisorctl start newstream'
stopg='sudo supervisorctl stop newstream'
restart_gunicorn='sudo supervisorctl restart newstream'

cmd="$rsync && $ssh '${source} && ${restart_gunicorn}'"
if [ $isxgulp = 'true' ]; then
    eval $xgulp
fi
if [ $ismigrate = 'true' ]; then
    # migrate script also restarts gunicorn
    cmd="$rsync && $ssh '${source} && ${migrate} && ${restart_gunicorn}'"
fi

echo $cmd
eval $cmd
