#!/bin/bash

ismigrate='false'
gitdeploy='false'

print_usage() {
    printf "%s\n" "Usage: ./deploy [-h] [-m]" "zero flags = rsync and restart" "-h is for help" "-m is for migration at remote django before restarting gunicorn"
}

while getopts 'mh' flag; do
    case "${flag}" in
        m) ismigrate='true' ;;
        h) print_usage
           exit 1 ;;
    esac
done

rsync="rsync -av --exclude '.git' --exclude 'node_modules' ./ diff-1:/srv/www/omp/"
ssh='ssh diff-1'
source='cd /srv/www/omp && source ~/.profile && source venv/bin/activate && export LC_ALL="en_US.UTF-8"'
migrate='python manage.py makemigrations && python manage.py migrate'
startg='sudo supervisorctl start omp'
stopg='sudo supervisorctl stop omp'
restart_gunicorn='sudo supervisorctl restart omp'

cmd="$rsync && $ssh '${source} && ${restart_gunicorn}'"
if [ $ismigrate = 'true' ]; then
    # migrate script also restarts gunicorn
    cmd="$rsync && $ssh '${source} && ${migrate} && ${restart_gunicorn}'"
fi

echo $cmd
eval $cmd
