# Generated by Django 3.0.8 on 2020-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200814_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='donationform',
            name='allowed_gateways',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
