# Generated by Django 3.0.8 on 2020-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20200907_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_user_first_donation',
        ),
    ]
