# Generated by Django 3.0.8 on 2020-09-13 18:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20200913_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='parent_donation',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='object_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recurring_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('processing', 'Processing'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive')], default='inactive', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('subscription', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_metas', to='donations.Subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment Meta',
                'verbose_name_plural': 'Subscription Payment Metas',
                'ordering': ['-id'],
            },
        ),
    ]
