# Generated by Django 3.0.8 on 2020-09-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20200915_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Define fixed donation amount if you chose "Fixed Amount" for your Amount Type.', max_digits=20, null=True),
        ),
    ]
