# Generated by Django 3.0.8 on 2020-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_auto_20200915_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='is_active',
        ),
    ]
