# Generated by Django 3.0.8 on 2020-11-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_auto_20200924_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='order_number',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='object_id',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
