# Generated by Django 3.0.8 on 2020-12-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20201121_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('revoked', 'Revoked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
    ]
