# Generated by Django 3.0.8 on 2021-03-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20210308_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Subscription'),
        ),
    ]