# Generated by Django 3.0.14 on 2021-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_auto_20210427_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='default_frequency',
            field=models.CharField(choices=[('onetime', 'One-time'), ('monthly', 'Monthly')], blank=False, default='onetime', max_length=20),
            preserve_default=False,
        ),
    ]
