# Generated by Django 3.1.11 on 2021-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0032_auto_20210521_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='donation_footer_text_en',
        ),
        migrations.RemoveField(
            model_name='donationform',
            name='donation_footer_text_id_id',
        ),
        migrations.RemoveField(
            model_name='donationform',
            name='donation_footer_text_ms',
        ),
        migrations.RemoveField(
            model_name='donationform',
            name='donation_footer_text_tl',
        ),
        migrations.RemoveField(
            model_name='donationform',
            name='donation_footer_text_zh_hant',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='choices_en',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='choices_id_id',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='choices_ms',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='choices_tl',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='choices_zh_hant',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='default_value_en',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='default_value_id_id',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='default_value_ms',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='default_value_tl',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='default_value_zh_hant',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='help_text_en',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='help_text_id_id',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='help_text_ms',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='help_text_tl',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='help_text_zh_hant',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='label_id_id',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='label_ms',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='label_tl',
        ),
        migrations.RemoveField(
            model_name='donationmetafield',
            name='label_zh_hant',
        ),
    ]
