# Generated by Django 3.1.11 on 2021-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0036_setup_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='guest_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempdonation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
