# Generated by Django 3.1.11 on 2022-01-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0037_auto_20211129_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Define maximum amount per donation.', max_digits=20, null=True),
        ),
    ]
