# Generated by Django 3.1.11 on 2023-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0040_init_subscription_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninstance',
            name='recurring_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('processing', 'Processing'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive'), ('payment_failed', 'Payment_failed')], default='inactive', max_length=255, null=True),
        ),
    ]
