# Generated by Django 3.1.11 on 2023-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0041_auto_20230517_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninstance',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('declined-checkout', 'Declined checkout'), ('by-admin', 'By admin'), ('by-donor', 'By donor'), ('payments-failed', 'Payments failed')], max_length=30, null=True),
        ),
    ]
