# Generated by Django 3.1.11 on 2023-06-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0042_subscriptioninstance_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninstance',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tempdonation',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('daily', 'Daily')], max_length=20, null=True),
        ),
    ]
