# Generated by Django 3.2.20 on 2023-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0043_subscriptioninstance_recurring_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninstance',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('declined-checkout', 'Declined checkout'), ('by-admin', 'By admin'), ('by-donor', 'By donor'), ('payments-failed', 'Payments failed'), ('payments-failed-resolved', 'Payments failed resolved')], max_length=30, null=True),
        ),
    ]
