# Generated by Django 3.0.8 on 2020-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200821_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_api_publishable_key',
            field=models.CharField(blank=True, help_text='The Live API publishable key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_api_secret_key',
            field=models.CharField(blank=True, help_text='The Live API secret key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_testing_api_publishable_key',
            field=models.CharField(blank=True, help_text='The Testing API publishable key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_testing_api_secret_key',
            field=models.CharField(blank=True, help_text='The Testing API secret key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='The Secret for the Webhook used by the server for payment verification', max_length=255),
        ),
    ]
