# Generated by Django 3.0.8 on 2020-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20200825_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_product_id',
            field=models.CharField(help_text='Product ID accessible on your Stripe Dashboard', max_length=255, null=True),
        ),
    ]
