# Generated by Django 3.0.8 on 2020-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_auto_20200924_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_api_client_id',
            field=models.CharField(blank=True, help_text='The Live API Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_api_secret_key',
            field=models.CharField(blank=True, help_text='The Live API secret key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_sandbox_api_client_id',
            field=models.CharField(blank=True, help_text='The Sandbox API Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_sandbox_api_secret_key',
            field=models.CharField(blank=True, help_text='The Sandbox API secret key', max_length=255),
        ),
    ]
