# Generated by Django 3.0.8 on 2020-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_auto_20201013_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_api_webhook_id',
            field=models.CharField(blank=True, help_text='The Live API Webhook ID', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_sandbox_api_webhook_id',
            field=models.CharField(blank=True, help_text='The Sandbox API Webhook ID', max_length=255),
        ),
    ]
