# Generated by Django 3.0.8 on 2020-12-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_sitesettings_limit_fiveactions_per_fivemins'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donations_soft_delete_mode',
            field=models.BooleanField(default=True, help_text='Enabling this ensure Donations and Subscriptions will still exist in the database even after being deleted from wagtail admin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='limit_fiveactions_per_fivemins',
            field=models.BooleanField(default=True, help_text='Enable this will limit donor to only 5 subscription update-actions(edit/pause/resume) every 5 minutes'),
        ),
    ]
