# Generated by Django 3.0.8 on 2021-02-22 01:00

from django.db import migrations

from site_settings.models import GATEWAY_MANUAL, GATEWAY_OFFLINE

def populate_more_supported_gateways(apps, schema_editor):
    # We can't import the PaymentGateway model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PaymentGateway = apps.get_model('site_settings', 'PaymentGateway')

    supported_gateways = [
        {
            "title": GATEWAY_MANUAL,
            "frontend_label_attr_name": "manual_frontend_label",
            "list_order": 3
        },
        {
            "title": GATEWAY_OFFLINE,
            "frontend_label_attr_name": "offline_frontend_label",
            "list_order": 4
        }
    ]

    for gateway_args in supported_gateways:
        gateway = PaymentGateway(**gateway_args)
        gateway.save()

class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_auto_20210106_0941'),
    ]

    operations = [
        migrations.RunPython(populate_more_supported_gateways),
    ]