# Generated by Django 3.0.8 on 2021-02-24 17:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0020_sitesettings_offline_thankyou_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label_en',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label_id_id',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label_ms',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label_tl',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label_zh_hant',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label_en',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label_id_id',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label_ms',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label_tl',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label_zh_hant',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_instructions_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_instructions_text_id_id',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_instructions_text_ms',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_instructions_text_tl',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_instructions_text_zh_hant',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_thankyou_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_thankyou_text_id_id',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_thankyou_text_ms',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_thankyou_text_tl',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_thankyou_text_zh_hant',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
