# Generated by Django 3.0.8 on 2021-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0021_auto_20210224_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='paypal_old_frontend_label',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label_en',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label_id_id',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label_ms',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label_tl',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label_zh_hant',
            field=models.CharField(default='PayPal - Legacy', help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255, null=True),
        ),
    ]
