# Generated by Django 3.1.11 on 2021-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0024_auto_20210310_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetafield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
