# Generated by Django 3.1.11 on 2021-06-08 15:14

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0031_auto_20210608_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_name',
            field=i18nfield.fields.I18nCharField(blank=True, max_length=255),
        ),
    ]
