# Generated by Django 3.1.11 on 2023-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0034_auto_20230517_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='social_login_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Product ID accessible on your Stripe Dashboard', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stripe_testing_product_id',
            field=models.CharField(blank=True, help_text='Testing Product ID accessible on your Stripe Dashboard', max_length=255, null=True),
        ),
    ]
