# Generated by Django 3.1.11 on 2023-05-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0035_auto_20230518_1022'),
    ]

    # This is necessary for now because old default values were set in migrations prior this one
    def reset_defaults_to_none(apps, schema_editor):
        Site = apps.get_model('wagtailcore.Site')
        SiteSettings = apps.get_model('site_settings', 'SiteSettings')
        ss = SiteSettings.objects.get(pk=1)
        
        ss.notify_admin_account_created = None
        ss.notify_admin_account_deleted = None
        ss.notify_admin_new_donation = None
        ss.notify_admin_donation_revoked = None
        ss.notify_admin_monthly_renewal = None
        ss.notify_admin_new_recurring = None
        ss.notify_admin_recurring_adjusted = None
        ss.notify_admin_recurring_rescheduled = None
        ss.notify_admin_recurring_paused = None
        ss.notify_admin_recurring_resumed = None
        ss.notify_admin_recurring_cancelled = None
        ss.notify_admin_donation_error = None

        ss.social_login_enabled = None
        ss.social_skip_signup = None
        
        ss.google_login_enabled = None
        ss.facebook_login_enabled = None
        ss.twitter_login_enabled = None

        ss.sandbox_mode = None
        ss.currency = "None"

        ss.donation_updates_rate_limiter = None
        ss.donations_soft_delete_mode = None
        
        ss.save()

    def reverse_operation(apps, schema_editor):
        pass

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('USD', 'US Dollars ($)'), ('EUR', 'Euros (€)'), ('GBP', 'Pounds Sterling (£)'), ('AUD', 'Australian Dollars ($)'), ('BRL', 'Brazilian Real (R$)'), ('CAD', 'Canadian Dollars ($)'), ('CZK', 'Czech Koruna (Kč)'), ('DKK', 'Danish Krone (\xa0kr.\xa0)'), ('HKD', 'Hong Kong Dollar ($)'), ('HUF', 'Hungarian Forint (Ft)'), ('ILS', 'Israeli Shekel (₪)'), ('JPY', 'Japanese Yen (¥)'), ('MYR', 'Malaysian Ringgits (RM)'), ('MXN', 'Mexican Peso ($)'), ('MAD', 'Moroccan Dirham (.د.م)'), ('NZD', 'New Zealand Dollar ($)'), ('NOK', 'Norwegian Krone (kr.)'), ('PHP', 'Philippine Pesos (₱)'), ('PLN', 'Polish Zloty (zł)'), ('SGD', 'Singapore Dollar ($)'), ('KRW', 'South Korean Won (₩)'), ('ZAR', 'South African Rand (R)'), ('SEK', 'Swedish Krona (\xa0kr.\xa0)'), ('CHF', 'Swiss Franc (CHF)'), ('TWD', 'Taiwan New Dollars (NT$)'), ('THB', 'Thai Baht (฿)'), ('INR', 'Indian Rupee (₹)'), ('TRY', 'Turkish Lira (₺)'), ('RUB', 'Russian Rubles (₽)'), ('AED', 'United Arab Emirates dirham (د.إ)'), ('AMD', 'Armenian dram (AMD)'), ('ANG', 'Netherlands Antillean guilder (ƒ)'), ('ARS', 'Argentine peso ($)'), ('AWG', 'Aruban florin (ƒ)'), ('BAM', 'Bosnia and Herzegovina convertible mark (KM)'), ('BDT', 'Bangladeshi taka (৳)'), ('BMD', 'Bermudian dollar (BD$)'), ('BND', 'Brunei dollar (B$)'), ('BOB', 'Bolivian boliviano (Bs.)'), ('BSD', 'Bahamian dollar (B$)'), ('BWP', 'Botswana pula (P)'), ('BZD', 'Belizean dollar (BZ$)'), ('CLP', 'Chilean peso ($)'), ('CNY', 'Chinese yuan (¥)'), ('COP', 'Colombian peso ($)'), ('CRC', 'Costa Rican colón (₡)'), ('DOP', 'Dominican peso (RD$)'), ('EGP', 'Egyptian pound (E£)'), ('GIP', 'Gibraltar pound (£)'), ('GTQ', 'Guatemalan quetzal (Q)'), ('HNL', 'Honduran lempira (L)'), ('HRK', 'Croatian kuna (kn)'), ('IDR', 'Indonesian rupiah (Rp)'), ('ISK', 'Icelandic króna (kr)'), ('JMD', 'Jamaican dollar (j$)'), ('KES', 'Kenyan shilling (KSh)'), ('KYD', 'Cayman Islands dollar (KY$)'), ('MKD', 'Macedonian denar (ден)'), ('NPR', 'Nepalese rupee (₨)'), ('PEN', 'Peruvian nuevo sol (S/.)'), ('PKR', 'Pakistani rupee (₨)'), ('RON', 'Romanian leu (L)'), ('SAR', 'Saudi riyal (ر.س)'), ('SZL', 'Swazi lilangeni (E)'), ('TOP', 'Tongan paʻanga (T$)'), ('TZS', 'Tanzanian shilling (TSh)'), ('UAH', 'Ukrainian hryvnia (₴)'), ('UYU', 'Uruguayan peso ($U)'), ('XCD', 'East Caribbean dollar (EC$)'), ('AFN', 'Afghan afghani (؋)'), ('ALL', 'Albanian lek (L)'), ('AOA', 'Angolan kwanza (Kz)'), ('AZN', 'Azerbaijani manat (AZN)'), ('BBD', 'Barbadian dollar ($)'), ('BGN', 'Bulgarian lev (лв.)'), ('BIF', 'Burundian franc (Fr)'), ('CDF', 'Congolese franc (Fr)'), ('CVE', 'Cape Verdean escudo ($)'), ('DJF', 'Djiboutian franc (Fr)'), ('DZD', 'Algerian dinar (د.ج)'), ('ETB', 'Ethiopian birr (Br)'), ('FJD', 'Fijian dollar ($)'), ('FKP', 'Falkland Islands pound (£)'), ('GEL', 'Georgian lari (₾)'), ('GMD', 'Gambian dalasi (D)'), ('GNF', 'Guinean franc (Fr)'), ('GYD', 'Guyanese dollar ($)'), ('HTG', 'Haitian gourde (G)'), ('KGS', 'Kyrgyzstani som (сом)'), ('KHR', 'Cambodian riel (៛)'), ('KMF', 'Comorian franc (Fr)'), ('KZT', 'Kazakhstani tenge (KZT)'), ('LAK', 'Lao kip (₭)'), ('LBP', 'Lebanese pound (ل.ل)'), ('LKR', 'Sri Lankan rupee (රු)'), ('LRD', 'Liberian dollar ($)'), ('LSL', 'Lesotho loti (L)'), ('MDL', 'Moldovan leu (MDL)'), ('MGA', 'Malagasy ariary (Ar)'), ('MMK', 'Burmese kyat (Ks)'), ('MNT', 'Mongolian tögrög (₮)'), ('MOP', 'Macanese pataca (P)'), ('MRO', 'Mauritanian ouguiya (UM)'), ('MUR', 'Mauritian rupee (₨)'), ('MVR', 'Maldivian rufiyaa (.ރ)'), ('MWK', 'Malawian kwacha (MK)'), ('MZN', 'Mozambican metical (MT)'), ('NAD', 'Namibian dollar ($)'), ('NGN', 'Nigerian naira (₦)'), ('NIO', 'Nicaraguan córdoba (C$)'), ('PAB', 'Panamanian balboa (B/.)'), ('PGK', 'Papua New Guinean kina (K)'), ('PYG', 'Paraguayan guaraní (₲)'), ('QAR', 'Qatari riyal (ر.ق)'), ('RSD', 'Serbian dinar (дин.)'), ('RWF', 'Rwandan franc (Fr)'), ('SBD', 'Solomon Islands dollar ($)'), ('SCR', 'Seychellois rupee (₨)'), ('SHP', 'Saint Helena pound (£)'), ('SLL', 'Sierra Leonean leone (Le)'), ('SOS', 'Somali shilling (Sh)'), ('SRD', 'Surinamese dollar ($)'), ('STD', 'São Tomé and Príncipe dobra (Db)'), ('TJS', 'Tajikistani somoni (ЅМ)'), ('TTD', 'Trinidad and Tobago dollar ($)'), ('UGX', 'Ugandan shilling (UGX)'), ('UZS', 'Uzbekistani som (UZS)'), ('VND', 'Vietnamese đồng (₫)'), ('VUV', 'Vanuatu vatu (Vt)'), ('WST', 'Samoan tālā (T)'), ('XAF', 'Central African CFA franc (CFA)'), ('XOF', 'West African CFA franc (CFA)'), ('XPF', 'CFP franc (Fr)'), ('YER', 'Yemeni rial (﷼)'), ('ZMW', 'Zambian kwacha (ZK)')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='donation_updates_rate_limiter',
            field=models.BooleanField(help_text='Enable this will limit donor to only 5 subscription update-actions(edit/pause/resume) every 5 minutes', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='donations_soft_delete_mode',
            field=models.BooleanField(help_text='Enabling this will ensure Donations and Subscriptions will still exist in the database even after being deleted from wagtail admin', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_login_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_login_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_account_created',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_account_deleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_donation_error',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_donation_revoked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_monthly_renewal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_new_donation',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_new_recurring',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_recurring_adjusted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_recurring_cancelled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_recurring_paused',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_recurring_rescheduled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_admin_recurring_resumed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sandbox_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_login_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_skip_signup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_login_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(reset_defaults_to_none, reverse_operation),
    ]
