import environ

# Newstream can receive environment variables for most of the site settings
# defined in site_settings.models.SiteSettings
# Values from environment variables have a higher priority than values saved in database
# thus default values should all be None to prevent unwanted overrides
# Note: terraform doesn't have to provide values for all env vars here, we're just building the capability
site_settings_envvars = environ.Env(
    # Emails > General
    NEWSTREAM_DEFAULT_FROM_EMAIL=(str, None),
    NEWSTREAM_DEFAULT_FROM_NAME=(str, None),
    NEWSTREAM_ORG_CONTACT_EMAIL=(str, None),
    NEWSTREAM_ADMIN_EMAILS=(str, None),

    # Emails > Admin Emails
    NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_CREATED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_DELETED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_NEW_DONATION=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_DONATION_REVOKED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_MONTHLY_RENEWAL=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_NEW_RECURRING=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_RECURRING_ADJUSTED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESCHEDULED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_RECURRING_PAUSED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESUMED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_RECURRING_CANCELLED=(bool, None),
    NEWSTREAM_NOTIFY_ADMIN_DONATION_ERROR=(bool, None),

    # Donor Signup > General
    NEWSTREAM_SOCIAL_LOGIN_ENABLED=(bool, None),
    NEWSTREAM_SOCIAL_SKIP_SIGNUP=(bool, None),

    # Donor Signup > Google
    NEWSTREAM_GOOGLE_LOGIN_ENABLED=(bool, None),

    # Donor Signup > Facebook
    NEWSTREAM_FACEBOOK_LOGIN_ENABLED=(bool, None),

    # Donor Signup > Twitter
    NEWSTREAM_TWITTER_LOGIN_ENABLED=(bool, None),

    # Donations > General
    NEWSTREAM_SANDBOX_MODE=(bool, None),
    NEWSTREAM_CURRENCY=(str, None),
    NEWSTREAM_DONATION_UPDATES_RATE_LIMITER=(bool, None),
    NEWSTREAM_DONATIONS_SOFT_DELETE_MODE=(bool, None),

    # Donations > 2C2P(Credit Card)
    NEWSTREAM__2C2P_FRONTEND_LABEL=(str, None),
    NEWSTREAM__2C2P_TESTING_MERCHANT_ID=(str, None),
    NEWSTREAM__2C2P_TESTING_SECRET_KEY=(str, None),
    NEWSTREAM__2C2P_MERCHANT_ID=(str, None),
    NEWSTREAM__2C2P_SECRET_KEY=(str, None),

    # Donations > PayPal
    NEWSTREAM_PAYPAL_FRONTEND_LABEL=(str, None),
    NEWSTREAM_PAYPAL_SANDBOX_API_PRODUCT_ID=(str, None),
    NEWSTREAM_PAYPAL_SANDBOX_API_CLIENT_ID=(str, None),
    NEWSTREAM_PAYPAL_SANDBOX_API_SECRET_KEY=(str, None),
    NEWSTREAM_PAYPAL_SANDBOX_API_WEBHOOK_ID=(str, None),
    NEWSTREAM_PAYPAL_API_PRODUCT_ID=(str, None),
    NEWSTREAM_PAYPAL_API_CLIENT_ID=(str, None),
    NEWSTREAM_PAYPAL_API_SECRET_KEY=(str, None),
    NEWSTREAM_PAYPAL_API_WEBHOOK_ID=(str, None),

    # Donations > PayPal(Legacy)
    NEWSTREAM_PAYPAL_LEGACY_FRONTEND_LABEL=(str, None),

    # Donations > Stripe
    NEWSTREAM_STRIPE_FRONTEND_LABEL=(str, None),
    NEWSTREAM_STRIPE_TESTING_WEBHOOK_SECRET=(str, None),
    NEWSTREAM_STRIPE_TESTING_PRODUCT_ID=(str, None),
    NEWSTREAM_STRIPE_TESTING_API_PUBLISHABLE_KEY=(str, None),
    NEWSTREAM_STRIPE_TESTING_API_SECRET_KEY=(str, None),
    NEWSTREAM_STRIPE_WEBHOOK_SECRET=(str, None),
    NEWSTREAM_STRIPE_PRODUCT_ID=(str, None),
    NEWSTREAM_STRIPE_API_PUBLISHABLE_KEY=(str, None),
    NEWSTREAM_STRIPE_API_SECRET_KEY=(str, None),

    # Donations > Others
    NEWSTREAM_MANUAL_FRONTEND_LABEL=(str, None),
    NEWSTREAM_OFFLINE_FRONTEND_LABEL=(str, None),

    # Appearance > General
    NEWSTREAM_FULL_ORG_NAME=(str, None),
    NEWSTREAM_SHORT_ORG_NAME=(str, None),

    # Appearance > Footer
    NEWSTREAM_PRIVACY_POLICY_LINK=(str, None),
)

# Emails > General
NEWSTREAM_DEFAULT_FROM_EMAIL = site_settings_envvars("NEWSTREAM_DEFAULT_FROM_EMAIL")
NEWSTREAM_DEFAULT_FROM_NAME = site_settings_envvars("NEWSTREAM_DEFAULT_FROM_NAME")
NEWSTREAM_ORG_CONTACT_EMAIL = site_settings_envvars("NEWSTREAM_ORG_CONTACT_EMAIL")
NEWSTREAM_ADMIN_EMAILS = site_settings_envvars("NEWSTREAM_ADMIN_EMAILS")

# Emails > Admin Emails
NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_CREATED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_CREATED")
NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_DELETED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_DELETED")
NEWSTREAM_NOTIFY_ADMIN_NEW_DONATION = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_NEW_DONATION")
NEWSTREAM_NOTIFY_ADMIN_DONATION_REVOKED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_DONATION_REVOKED")
NEWSTREAM_NOTIFY_ADMIN_MONTHLY_RENEWAL = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_MONTHLY_RENEWAL")
NEWSTREAM_NOTIFY_ADMIN_NEW_RECURRING = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_NEW_RECURRING")
NEWSTREAM_NOTIFY_ADMIN_RECURRING_ADJUSTED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_RECURRING_ADJUSTED")
NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESCHEDULED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESCHEDULED")
NEWSTREAM_NOTIFY_ADMIN_RECURRING_PAUSED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_RECURRING_PAUSED")
NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESUMED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESUMED")
NEWSTREAM_NOTIFY_ADMIN_RECURRING_CANCELLED = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_RECURRING_CANCELLED")
NEWSTREAM_NOTIFY_ADMIN_DONATION_ERROR = site_settings_envvars("NEWSTREAM_NOTIFY_ADMIN_DONATION_ERROR")

# Donor Signup > General
NEWSTREAM_SOCIAL_LOGIN_ENABLED = site_settings_envvars("NEWSTREAM_SOCIAL_LOGIN_ENABLED")
NEWSTREAM_SOCIAL_SKIP_SIGNUP = site_settings_envvars("NEWSTREAM_SOCIAL_SKIP_SIGNUP")

# Donor Signup > Google
NEWSTREAM_GOOGLE_LOGIN_ENABLED = site_settings_envvars("NEWSTREAM_GOOGLE_LOGIN_ENABLED")

# Donor Signup > Facebook
NEWSTREAM_FACEBOOK_LOGIN_ENABLED = site_settings_envvars("NEWSTREAM_FACEBOOK_LOGIN_ENABLED")

# Donor Signup > Twitter
NEWSTREAM_TWITTER_LOGIN_ENABLED = site_settings_envvars("NEWSTREAM_TWITTER_LOGIN_ENABLED")

# Donations > General
NEWSTREAM_SANDBOX_MODE = site_settings_envvars("NEWSTREAM_SANDBOX_MODE")
NEWSTREAM_CURRENCY = site_settings_envvars("NEWSTREAM_CURRENCY")
NEWSTREAM_DONATION_UPDATES_RATE_LIMITER = site_settings_envvars("NEWSTREAM_DONATION_UPDATES_RATE_LIMITER")
NEWSTREAM_DONATIONS_SOFT_DELETE_MODE = site_settings_envvars("NEWSTREAM_DONATIONS_SOFT_DELETE_MODE")

# Donations > 2C2P(Credit Card)
NEWSTREAM__2C2P_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM__2C2P_FRONTEND_LABEL")
NEWSTREAM__2C2P_TESTING_MERCHANT_ID = site_settings_envvars("NEWSTREAM__2C2P_TESTING_MERCHANT_ID")
NEWSTREAM__2C2P_TESTING_SECRET_KEY = site_settings_envvars("NEWSTREAM__2C2P_TESTING_SECRET_KEY")
NEWSTREAM__2C2P_MERCHANT_ID = site_settings_envvars("NEWSTREAM__2C2P_MERCHANT_ID")
NEWSTREAM__2C2P_SECRET_KEY = site_settings_envvars("NEWSTREAM__2C2P_SECRET_KEY")

# Donations > PayPal
NEWSTREAM_PAYPAL_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM_PAYPAL_FRONTEND_LABEL")
NEWSTREAM_PAYPAL_SANDBOX_API_PRODUCT_ID = site_settings_envvars("NEWSTREAM_PAYPAL_SANDBOX_API_PRODUCT_ID")
NEWSTREAM_PAYPAL_SANDBOX_API_CLIENT_ID = site_settings_envvars("NEWSTREAM_PAYPAL_SANDBOX_API_CLIENT_ID")
NEWSTREAM_PAYPAL_SANDBOX_API_SECRET_KEY = site_settings_envvars("NEWSTREAM_PAYPAL_SANDBOX_API_SECRET_KEY")
NEWSTREAM_PAYPAL_SANDBOX_API_WEBHOOK_ID = site_settings_envvars("NEWSTREAM_PAYPAL_SANDBOX_API_WEBHOOK_ID")
NEWSTREAM_PAYPAL_API_PRODUCT_ID = site_settings_envvars("NEWSTREAM_PAYPAL_API_PRODUCT_ID")
NEWSTREAM_PAYPAL_API_CLIENT_ID = site_settings_envvars("NEWSTREAM_PAYPAL_API_CLIENT_ID")
NEWSTREAM_PAYPAL_API_SECRET_KEY = site_settings_envvars("NEWSTREAM_PAYPAL_API_SECRET_KEY")
NEWSTREAM_PAYPAL_API_WEBHOOK_ID = site_settings_envvars("NEWSTREAM_PAYPAL_API_WEBHOOK_ID")

# Donations > PayPal(Legacy)
NEWSTREAM_PAYPAL_LEGACY_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM_PAYPAL_LEGACY_FRONTEND_LABEL")

# Donations > Stripe
NEWSTREAM_STRIPE_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM_STRIPE_FRONTEND_LABEL")
NEWSTREAM_STRIPE_TESTING_WEBHOOK_SECRET = site_settings_envvars("NEWSTREAM_STRIPE_TESTING_WEBHOOK_SECRET")
NEWSTREAM_STRIPE_TESTING_PRODUCT_ID = site_settings_envvars("NEWSTREAM_STRIPE_TESTING_PRODUCT_ID")
NEWSTREAM_STRIPE_TESTING_API_PUBLISHABLE_KEY = site_settings_envvars("NEWSTREAM_STRIPE_TESTING_API_PUBLISHABLE_KEY")
NEWSTREAM_STRIPE_TESTING_API_SECRET_KEY = site_settings_envvars("NEWSTREAM_STRIPE_TESTING_API_SECRET_KEY")
NEWSTREAM_STRIPE_WEBHOOK_SECRET = site_settings_envvars("NEWSTREAM_STRIPE_WEBHOOK_SECRET")
NEWSTREAM_STRIPE_PRODUCT_ID = site_settings_envvars("NEWSTREAM_STRIPE_PRODUCT_ID")
NEWSTREAM_STRIPE_API_PUBLISHABLE_KEY = site_settings_envvars("NEWSTREAM_STRIPE_API_PUBLISHABLE_KEY")
NEWSTREAM_STRIPE_API_SECRET_KEY = site_settings_envvars("NEWSTREAM_STRIPE_API_SECRET_KEY")

# Donations > Others
NEWSTREAM_MANUAL_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM_MANUAL_FRONTEND_LABEL")
NEWSTREAM_OFFLINE_FRONTEND_LABEL = site_settings_envvars("NEWSTREAM_OFFLINE_FRONTEND_LABEL")

# Appearance > General
NEWSTREAM_FULL_ORG_NAME = site_settings_envvars("NEWSTREAM_FULL_ORG_NAME")
NEWSTREAM_SHORT_ORG_NAME = site_settings_envvars("NEWSTREAM_SHORT_ORG_NAME")

# Appearance > Footer
NEWSTREAM_PRIVACY_POLICY_LINK = site_settings_envvars("NEWSTREAM_PRIVACY_POLICY_LINK")