# Generated by Django 3.0.8 on 2020-12-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_auto_20201204_2254'),
        ('newstream_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionUpdatesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('update-subscription', 'update-subscription'), ('toggle-subscription', 'toggle-subscription')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Subscription')),
                ('user', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsupdateslogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription Updates Log',
                'verbose_name_plural': 'User Subscription Updates Logs',
                'ordering': ['-id'],
            },
        ),
    ]
