# Generated by Django 3.0.8 on 2021-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0003_auto_20201219_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionupdateslog',
            name='action_type',
            field=models.CharField(choices=[('update-subscription', 'update-subscription'), ('pause-subscription', 'pause-subscription'), ('resume-subscription', 'resume-subscription'), ('cancel-subscription', 'cancel-subscription')], max_length=255, null=True),
        ),
    ]
