# Generated by Django 3.0.8 on 2021-03-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0024_auto_20210223_1803'),
        ('newstream_user', '0005_usersubscriptionupdateslog_action_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionupdateslog',
            name='action_type',
            field=models.CharField(choices=[('update-subscription', 'update-subscription'), ('pause-subscription', 'pause-subscription'), ('resume-subscription', 'resume-subscription'), ('cancel-subscription', 'cancel-subscription'), ('manual-update-status', 'manual-update-status')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserDonationUpdatesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('manual-update-status', 'manual-update-status')], max_length=255, null=True)),
                ('action_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Donation')),
                ('user', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donationupdateslogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Donation Updates Log',
                'verbose_name_plural': 'User Donation Updates Logs',
                'ordering': ['-id'],
            },
        ),
    ]
