# Generated by Django 3.0.8 on 2021-04-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0008_auto_20210306_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=10),
        ),
    ]
