# Generated by Django 3.1.11 on 2021-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0010_auto_20210521_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hant', 'Traditional Chinese')], max_length=10),
        ),
    ]
