# Generated by Django 3.1.11 on 2021-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstream_user', '0011_auto_20210531_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('zh-hant', 'Traditional Chinese'), ('en', 'English')], max_length=10),
        ),
    ]
