# Generated by Django 3.0.8 on 2020-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Static Page', 'verbose_name_plural': 'Static Pages'},
        ),
    ]
