# Generated by Django 3.1.11 on 2021-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210521_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_id_id',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_ms',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_tl',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_zh_hant',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body_id_id',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body_ms',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body_tl',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body_zh_hant',
        ),
    ]
