# Generated by Django 3.1.11 on 2021-05-30 04:48

from django.db import migrations
import json

def initial_data(apps, schema_editor):

    ContentType = apps.get_model('contenttypes.ContentType')
    Group = apps.get_model('auth.Group')
    Page = apps.get_model('wagtailcore.Page')
    HomePage = apps.get_model('pages.HomePage')
    Site = apps.get_model('wagtailcore.Site')
    GroupPagePermission = apps.get_model('wagtailcore.GroupPagePermission')

    # Load the homepage content type
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage',
        app_label='pages'
    )

    # Remove the default site which is installed by wagtail
    home_page = HomePage.objects.create(
        title="Home",
        slug='home',
        content_type=homepage_content_type,
        path='00010002',
        depth=2,
        numchild=0,
        url_path='/home2/',
        body=json.dumps(
            [
              {
                "type": "full_width_section",
                "value": {
                  "width_css": "container",
                  "background_color_css": "bg-primary-light",
                  "content": [
                    {
                      "type": "single_column_row",
                      "value": {
                        "alignment_css": "column-horz-align-center",
                        "content": [
                          {
                            "type": "text_block",
                            "value": "<p data-block-key=\"m33fq\">Welcome to your new newstream installation</p><p data-block-key=\"9jlqq\">"
                                     "<a href=\"/donations/donate\">Donation Form</a></p><p data-block-key=\"6p67c\"><a href=\"/admin\">Admin Site</a></p>",
                            "id": "19802651-8a7b-40fe-858d-9f6ed8ff6d96"
                          }
                        ]
                      },
                      "id": "a5f7dc54-d3b5-4687-b200-ed81f0962716"
                    }
                  ]
                },
                "id": "c7284666-5b62-4925-8121-e2aa74f3c8c2"
              }
            ]
        )
    )

    default_site = Site.objects.get(
        hostname='localhost',
    )
    default_site.root_page_id = home_page.id
    default_site.save()
    
    Page.objects.filter(
        url_path='/home/',
    ).delete()

    home_page.url_path = '/home/'
    home_page.save()
    


#    root = Page.objects.create(
#        title="Root",
#        slug='root',
#        content_type=page_content_type,
#        path='0001',
#        depth=1,
#        numchild=1,
#        url_path='/',
#    )
#
#    # Create homepage
#    homepage = Page.objects.create(
#        title="Welcome to your new Wagtail site!",
#        slug='home',
#        content_type=page_content_type,
#        path='00010001',
#        depth=2,
#        numchild=0,
#        url_path='/home/',
#    )
#
#    # Create default site
#

#
# From production
# 

# id                         | 3
# path                       | 00010002
# depth                      | 2
# numchild                   | 1
# title                      | Support Hong Kong Free Press
# slug                       | home
# live                       | t
# has_unpublished_changes    | f
# url_path                   | /home/
# seo_title                  | 
# show_in_menus              | f
# search_description         | 
# go_live_at                 | 
# expire_at                  | 
# expired                    | f
# content_type_id            | 40
# owner_id                   | 1
# locked                     | f
# latest_revision_created_at | 2021-05-26 07:17:37.922391+00
# first_published_at         | 2020-08-14 14:20:50.071+00
# live_revision_id           | 43
# last_published_at          | 2021-05-26 07:17:37.945029+00
# draft_title                | Support Hong Kong Free Press
# locked_at                  | 
# locked_by_id               | 
# search_description_en      | 
# title_en                   | Support Hong Kong Free Press
# slug_en                    | home
# url_path_en                | /home/
# seo_title_en               | 
# translation_key            | b4f2da13-d85b-490f-98fa-31890560725f
# locale_id                  | 1
# alias_of_id                | 


def remove_initial_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_search_image'),
        ('wagtailcore', '0002_initial_data'),
        ('contenttypes', '__first__'),
    ]

    operations = [
         migrations.RunPython(initial_data, remove_initial_data),
    ]
