# Generated by Django 3.1.11 on 2021-05-30 04:48

from django.db import migrations
import json

def initial_data(apps, schema_editor):

    ContentType = apps.get_model('contenttypes.ContentType')
    Group = apps.get_model('auth.Group')
    Page = apps.get_model('wagtailcore.Page')
    HomePage = apps.get_model('pages.HomePage')
    Site = apps.get_model('wagtailcore.Site')
    GroupPagePermission = apps.get_model('wagtailcore.GroupPagePermission')

    # Load the homepage content type
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage',
        app_label='pages'
    )

    # Remove the default site which is installed by wagtail
    home_page = HomePage.objects.create(
        title="Home",
        slug='home',
        content_type=homepage_content_type,
        path='00010002',
        depth=2,
        numchild=0,
        url_path='/home2/',
        body=json.dumps(
            [
              {
                "type": "full_width_section",
                "value": {
                  "width_css": "container",
                  "background_color_css": "bg-primary-light",
                  "content": [
                    {
                      "type": "single_column_row",
                      "value": {
                        "alignment_css": "column-horz-align-center",
                        "content": [
                          {
                            "type": "text_block",
                            "value": "<p data-block-key=\"m33fq\">Welcome to your new newstream installation</p><p data-block-key=\"9jlqq\">"
                                     "<a href=\"/donations/donate\">Donation Form</a></p><p data-block-key=\"6p67c\"><a href=\"/admin\">Admin Site</a></p>",
                            "id": "19802651-8a7b-40fe-858d-9f6ed8ff6d96"
                          }
                        ]
                      },
                      "id": "a5f7dc54-d3b5-4687-b200-ed81f0962716"
                    }
                  ]
                },
                "id": "c7284666-5b62-4925-8121-e2aa74f3c8c2"
              }
            ]
        )
    )

    # Link the default site to the new homepage
    default_site = Site.objects.get(
        hostname='localhost',
    )
    default_site.root_page_id = home_page.id
    default_site.save()
    
    # Remove the previous wagtail demo homepage
    # We can only do this now that the default site has been updated, otherwise the 
    # default site would have been removed
    Page.objects.filter(
        url_path='/home/',
    ).delete()

    # Update our homepage to be at /home/
    # We couldn't do this before, as the wagtail homepage was in the way
    home_page.url_path = '/home/'
    home_page.save()
    

def remove_initial_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_search_image'),
        ('wagtailcore', '0002_initial_data'),
        ('contenttypes', '__first__'),
    ]

    operations = [
         migrations.RunPython(initial_data, remove_initial_data),
    ]
