# Generated by Django 3.0.5 on 2020-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_in_mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
