version: "3.8"

networks:
  default:
    external:
      name: cloudbuild

services:
  database:
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./schema.sql:/schema.sql

  app_init:
    environment:
      STRIPE_API_BASE: 'http://localstripe.newstream.local:8420'
      STRIPE_JS_URL: 'http://localstripe.newstream.local:8420/js.stripe.com/v3/'
      INIT_LOCALSTRIPE: 1
      RESET_NULLABLE_SITESETTINGS: 1
      NEWSTREAM_DEFAULT_FROM_EMAIL: 'newstream@diffractive.io'
      NEWSTREAM_ADMIN_EMAILS: 'admin@diffractive.io'
    image: "${IMAGE_PREFIX}newstream:${IMAGE_TAG}"

  app:
    environment:
      STRIPE_API_BASE: 'http://localstripe.newstream.local:8420'
      STRIPE_JS_URL: 'http://localstripe.newstream.local:8420/js.stripe.com/v3/'
      DEBUG: 1
      PY_AUTORELOAD: 1
      NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_CREATED: 1
      NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_DELETED: 1
      NEWSTREAM_NOTIFY_ADMIN_NEW_DONATION: 1
      NEWSTREAM_NOTIFY_ADMIN_DONATION_REVOKED: 1
      NEWSTREAM_NOTIFY_ADMIN_MONTHLY_RENEWAL: 1
      NEWSTREAM_NOTIFY_ADMIN_NEW_RECURRING: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_ADJUSTED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESCHEDULED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_PAUSED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESUMED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_CANCELLED: 1
      NEWSTREAM_NOTIFY_ADMIN_DONATION_ERROR: 1
      NEWSTREAM_SOCIAL_LOGIN_ENABLED: 0
      NEWSTREAM_SOCIAL_SKIP_SIGNUP: 0
      NEWSTREAM_GOOGLE_LOGIN_ENABLED: 0
      NEWSTREAM_FACEBOOK_LOGIN_ENABLED: 0
      NEWSTREAM_TWITTER_LOGIN_ENABLED: 0
      NEWSTREAM_SANDBOX_MODE: 1
      NEWSTREAM_CURRENCY: 'HKD'
      NEWSTREAM_DONATION_UPDATES_RATE_LIMITER: 1
      NEWSTREAM_DONATIONS_SOFT_DELETE_MODE: 1
      NEWSTREAM_STRIPE_TESTING_WEBHOOK_SECRET: 'whsec_TEST_WEBHOOK_KEY'
      NEWSTREAM_STRIPE_TESTING_PRODUCT_ID: 'prod_TEST_PRODUCT_ID'
      NEWSTREAM_STRIPE_TESTING_API_SECRET_KEY: 'sk_TEST_SECRET_KEY'
      NEWSTREAM_FULL_ORG_NAME: 'Diffractive Limited'
      NEWSTREAM_SHORT_ORG_NAME: 'Diffractive'
    image: "${IMAGE_PREFIX}newstream:${IMAGE_TAG}"

  localstripe:
    image: "${IMAGE_PREFIX}localstripe:latest"

  localpaypal:
    image: "${IMAGE_PREFIX}localpaypal:latest"

  selenium_tests:
    image: "${IMAGE_PREFIX}newstream-tests:${IMAGE_TAG}"
    environment:
      STRIPE_API_BASE: 'http://localstripe.newstream.local:8420'
      STRIPE_SECRET_KEY: 'sk_TEST_SECRET_KEY'
      PAYPAL_API_BASE: 'http://localpaypal.newstream.local:8410'
    volumes:
      - '/workspace/output:/notebooks/output'
