version: "3.8"

services:
  database:
    environment:
      POSTGRES_DB: newstream
      POSTGRES_USER: newstream
      POSTGRES_PASSWORD: newstream
    restart: always
    image: postgres:12
    expose:
      - "5432"
    networks:
      - newstream

  app_init:
    environment:
      RUN_MIGRATIONS: 1
      COLLECTSTATIC: 1
      TEST_DATA: 1
      DATABASE_NAME: newstream
      DATABASE_USER: newstream
      DATABASE_HOST: database
      DATABASE_PASSWORD: newstream
      DJANGO_SUPERUSER_EMAIL: newstream@test.local
      DJANGO_SUPERUSER_PASSWORD: newstream
      GS_FAKE_CREDENTIALS: 1
      GS_BUCKET_NAME: newstream-test-bucket
      GS_STORAGE_ENDPOINT: https://storage:4443
      GS_CUSTOM_ENDPOINT: /gcsmedia
    image: diffractive/newstream:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database:database
    depends_on:
      - database
      - mailhog
      - storage
    command: init
    networks:
      newstream:
        aliases:
          - app.newstream.local

  app:
    environment:
      TEST_DATA: 1
      DATABASE_NAME: newstream
      DATABASE_USER: newstream
      DATABASE_HOST: database
      DATABASE_PASSWORD: newstream
      DJANGO_SUPERUSER_EMAIL: newstream@test.local
      DJANGO_SUPERUSER_PASSWORD: newstream
      GS_FAKE_CREDENTIALS: 1
      GS_BUCKET_NAME: newstream-test-bucket
      GS_STORAGE_ENDPOINT: https://storage:4443
      GS_CUSTOM_ENDPOINT: /gcsmedia
    image: diffractive/newstream:latest
    links:
      - database:database
    command: run
    depends_on:
      app_init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      newstream:
        aliases:
          - app.newstream.local

  localstripe:
    image: adrienverge/localstripe:latest
    environment:
      MAX_PAYMENT_FAILURE_RETRIES: 3
    ports:
      - 8420:8420
    networks:
      newstream:
        aliases:
          - localstripe.newstream.local

  localpaypal:
    image: diffractive/localpaypal:latest
    environment:
      DATABASE_NAME: localpaypal
      DATABASE_USER: localpaypal
      DATABASE_PASSWORD: localpaypal
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    ports:
      - 8410:8410
    networks:
      newstream:
        aliases:
          - localpaypal.newstream.local

  storage:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443 # API
    networks:
      newstream:
        aliases:
          - storage.newstream.local
    volumes:
      - '../data:/data'
    command: -public-host storage.newstream.local

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      newstream:
        aliases:
          - mailhog.newstream.local

  selenium:
    image: seleniarm/standalone-chromium:4.1.0-alpha-20211218
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "127.0.0.1:4444:4444"
    environment:
      NODE_MAX_SESSION: 5
      GRID_MAX_SESSION: 5
      SE_NODE_MAX_SESSIONS: 5
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
    networks:
      - newstream
    profiles:
      - selenium

  selenium_tests:
    image: diffractive/newstream-tests:latest
    ports:
      - "127.0.0.1:8890:8890"
    environment:
      SELENIUM_RUNNER: "remote"
    volumes:
      - '../notebooks:/notebooks'
      - ./selenium-config.yaml:/etc/diffractive/selenium.yaml
    networks:
      - newstream
    depends_on:
      - app
      - selenium
      - localstripe
      - localpaypal
    profiles:
      - selenium

networks:
  newstream:
    driver: bridge
