version: "3.8"

services:

  database:
    ports:
      - "127.0.0.1:5432:5432"

  app_init:
    environment:
      STRIPE_API_BASE: 'http://localstripe.newstream.local:8420'
      STRIPE_JS_URL: 'http://localstripe.newstream.local:8420/js.stripe.com/v3/'
      INIT_LOCALSTRIPE: 1
      RESET_NULLABLE_SITESETTINGS: 1
      NEWSTREAM_DEFAULT_FROM_EMAIL: 'newstream@diffractive.io'
      NEWSTREAM_ADMIN_EMAILS: 'admin@diffractive.io'
    volumes:
      - '../django-app:/app'

  app:
    environment:
      STRIPE_API_BASE: 'http://localstripe.newstream.local:8420'
      STRIPE_JS_URL: 'http://localstripe.newstream.local:8420/js.stripe.com/v3/'
      TEST_DATA: 1
      DEBUG: 1
      PY_AUTORELOAD: 1
      NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_CREATED: 1
      NEWSTREAM_NOTIFY_ADMIN_ACCOUNT_DELETED: 1
      NEWSTREAM_NOTIFY_ADMIN_NEW_DONATION: 1
      NEWSTREAM_NOTIFY_ADMIN_DONATION_REVOKED: 1
      NEWSTREAM_NOTIFY_ADMIN_MONTHLY_RENEWAL: 1
      NEWSTREAM_NOTIFY_ADMIN_NEW_RECURRING: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_ADJUSTED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESCHEDULED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_PAUSED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_RESUMED: 1
      NEWSTREAM_NOTIFY_ADMIN_RECURRING_CANCELLED: 1
      NEWSTREAM_NOTIFY_ADMIN_DONATION_ERROR: 1
      NEWSTREAM_SOCIAL_LOGIN_ENABLED: 0
      NEWSTREAM_SOCIAL_SKIP_SIGNUP: 0
      NEWSTREAM_GOOGLE_LOGIN_ENABLED: 0
      NEWSTREAM_FACEBOOK_LOGIN_ENABLED: 0
      NEWSTREAM_TWITTER_LOGIN_ENABLED: 0
      NEWSTREAM_SANDBOX_MODE: 1
      NEWSTREAM_CURRENCY: 'HKD'
      NEWSTREAM_DONATION_UPDATES_RATE_LIMITER: 1
      NEWSTREAM_DONATIONS_SOFT_DELETE_MODE: 1
      NEWSTREAM_STRIPE_TESTING_WEBHOOK_SECRET: 'whsec_TEST_WEBHOOK_KEY'
      NEWSTREAM_STRIPE_TESTING_PRODUCT_ID: 'prod_TEST_PRODUCT_ID'
      NEWSTREAM_STRIPE_TESTING_API_SECRET_KEY: 'sk_TEST_SECRET_KEY'
    volumes:
      - '../django-app:/app'

  selenium_tests:
    volumes:
      - '../selenium-tests/test_scripts:/home/jupyter/notebooks/test_scripts'
      - '../selenium-tests/output:/home/jupyter/notebooks/output'
