# Generated by Django 3.0.8 on 2020-08-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0002_auto_20200804_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'verbose_name': 'Target Group', 'verbose_name_plural': 'Target Groups'},
        ),
    ]
