# Generated by Django 3.1.11 on 2021-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0003_auto_20200814_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body_en',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body_id_id',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body_ms',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body_tl',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body_zh_hant',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_en',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_id_id',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_ms',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_tl',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_zh_hant',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_id_id',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_ms',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_tl',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_zh_hant',
        ),
    ]
