# Generated by Django 3.0.14 on 2021-05-20 18:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0003_auto_20200814_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('subject_en', models.CharField(max_length=255, null=True)),
                ('plain_text', models.TextField()),
                ('plain_text_en', models.TextField(null=True)),
                ('html_body', wagtail.core.fields.RichTextField(blank=True)),
                ('html_body_en', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Email Template',
                'verbose_name_plural': 'Campaign Email Templates',
            },
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_campaigns.CampaignEmailTemplate'),
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
