# Generated by Django 3.0.5 on 2020-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0004_auto_20200430_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='from_address',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
