# Generated by Django 3.1.11 on 2021-05-31 06:53

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0004_auto_20210531_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='plain_text',
            field=i18nfield.fields.I18nTextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=i18nfield.fields.I18nCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=i18nfield.fields.I18nCharField(max_length=255),
        ),
    ]
