# Generated by Django 3.1.11 on 2021-05-31 15:15

from django.db import migrations
import i18nfield.fields
import newstream.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0005_auto_20210531_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=i18nfield.fields.I18nCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_body',
            field=newstream.fields.I18nRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='title',
            field=i18nfield.fields.I18nCharField(max_length=255),
        ),
    ]
