# Generated by Django 3.0.8 on 2020-08-11 20:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('donation_amount', models.FloatField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_user_first_donation', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('revoked', 'Revoked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255)),
                ('recurring_status', models.CharField(blank=True, choices=[('on-going', 'On-going'), ('cancelled', 'Cancelled'), ('non-recurring', 'Non-recurring')], default='non-recurring', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user_deleted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('stepped', 'Fixed Steps'), ('custom', 'Custom Amount')], max_length=20)),
                ('fixed_amount', models.FloatField(blank=True, help_text='Define fixed donation amount if you chose "Fixed Amount" for your Amount Type', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('donation_footer_text', wagtail.core.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Donation Form',
                'verbose_name_plural': 'Donation Forms',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('frontend_label', models.CharField(max_length=255)),
                ('list_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['list_order'],
            },
        ),
        migrations.CreateModel(
            name='DonationPaymentMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('donation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_metas', to='donations.Donation')),
            ],
            options={
                'verbose_name': 'Donation Payment Meta',
                'verbose_name_plural': 'Donation Payment Metas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DonationMetaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('form', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_meta_fields', to='donations.DonationForm')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('donation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='donations.Donation')),
            ],
            options={
                'verbose_name': 'Donation Meta',
                'verbose_name_plural': 'Donation Metas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='donationform',
            name='allowed_gateways',
            field=models.ManyToManyField(to='donations.PaymentGateway'),
        ),
        migrations.AddField(
            model_name='donation',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.DonationForm'),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.PaymentGateway'),
        ),
        migrations.AddField(
            model_name='donation',
            name='parent_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
        ),
    ]
