# Generated by Django 3.0.5 on 2020-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('list_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['list_order'],
            },
        ),
    ]
