# Generated by Django 3.0.5 on 2020-04-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestGateway',
            new_name='TestModel',
        ),
    ]
