# Generated by Django 3.0.8 on 2020-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='title',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
