# Generated by Django 3.0.8 on 2020-08-12 09:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20200812_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text_ind',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text_ms',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text_tl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text_zh_hant',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='choices_en',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', null=True, verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='choices_ind',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', null=True, verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='choices_ms',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', null=True, verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='choices_tl',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', null=True, verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='choices_zh_hant',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', null=True, verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='default_value_en',
            field=models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='default_value_ind',
            field=models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='default_value_ms',
            field=models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='default_value_tl',
            field=models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='default_value_zh_hant',
            field=models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='help_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='help_text_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='help_text_ms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='help_text_tl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='help_text_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='label_en',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='label_ind',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='label_ms',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='label_tl',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='label_zh_hant',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
    ]
