# Generated by Django 3.0.8 on 2020-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20200804_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='donationform',
            options={'ordering': ['title'], 'verbose_name': 'Donation Form', 'verbose_name_plural': 'Donation Forms'},
        ),
        migrations.AlterModelOptions(
            name='donationmeta',
            options={'ordering': ['-id'], 'verbose_name': 'Donation Meta', 'verbose_name_plural': 'Donation Metas'},
        ),
        migrations.AlterModelOptions(
            name='donationpaymentmeta',
            options={'ordering': ['-id'], 'verbose_name': 'Donation Payment Meta', 'verbose_name_plural': 'Donation Payment Metas'},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['list_order'], 'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
    ]
