# Generated by Django 3.0.5 on 2020-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20200419_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='donationform',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
