# Generated by Django 3.0.5 on 2020-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200403_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='fixed_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
