# Generated by Django 3.0.5 on 2020-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200423_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='frontend_label',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
