# Generated by Django 3.0.8 on 2020-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donor_linked_user_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donormeta',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donormetafield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.AddField(
            model_name='donation',
            name='linked_user_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='DonorMeta',
        ),
        migrations.DeleteModel(
            name='DonorMetaField',
        ),
    ]
