# Generated by Django 3.0.5 on 2020-04-23 16:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_paymentgateway_frontend_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
