# Generated by Django 3.0.8 on 2020-08-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200821_1058'),
        ('donations', '0004_auto_20200821_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentGateway'),
        ),
        migrations.AddField(
            model_name='donationform',
            name='allowed_gateways',
            field=models.ManyToManyField(to='site_settings.PaymentGateway'),
        ),
    ]
