# Generated by Django 3.0.8 on 2020-07-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='personal_footer_text',
        ),
    ]
