# Generated by Django 3.0.8 on 2020-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200829_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='recurring_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('non-recurring', 'Non-recurring')], default='non-recurring', max_length=255, null=True),
        ),
    ]
