# Generated by Django 3.0.7 on 2020-07-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200430_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_create_account',
        ),
    ]
