# Generated by Django 3.0.5 on 2020-04-06 11:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200406_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='amount_steps',
        ),
        migrations.CreateModel(
            name='AmountStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0)),
                ('form', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_steps', to='donations.DonationForm')),
            ],
        ),
    ]
