# Generated by Django 3.0.5 on 2020-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20200406_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='fixed_amount',
            field=models.FloatField(blank=True, help_text='Define fixed donation amount if you chose "Fixed Amount" for your Amount Type', null=True, verbose_name='Define Fixed Donation Amount'),
        ),
    ]
