# Generated by Django 3.0.7 on 2020-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_remove_donation_is_create_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_user_first_donation',
            field=models.BooleanField(default=False),
        ),
    ]
