# Generated by Django 3.0.7 on 2020-07-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_is_user_first_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='footer_text',
        ),
    ]
