# Generated by Django 3.0.8 on 2020-09-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20200907_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('revoked', 'Revoked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recurring_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('processing', 'Processing'), ('renewal-payment', 'Renewal-payment'), ('cancelled', 'Cancelled'), ('non-recurring', 'Non-recurring')], default='non-recurring', max_length=255, null=True),
        ),
    ]
