# Generated by Django 3.0.5 on 2020-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20200406_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='amount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('stepped', 'Fixed Steps'), ('custom', 'Custom Amount')], max_length=20, verbose_name='Donation Amount Type'),
        ),
    ]
