# Generated by Django 3.0.7 on 2020-07-09 16:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_remove_donationform_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='donation_footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Footer Text(Under Donation Details Form)'),
        ),
        migrations.AddField(
            model_name='donationform',
            name='personal_footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Footer Text(Under Personal Info Form)'),
        ),
    ]
