# Generated by Django 3.0.5 on 2020-04-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20200406_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('first_name', 'last_name', 'email')},
        ),
        migrations.RemoveField(
            model_name='donor',
            name='contact_number',
        ),
    ]
