# Generated by Django 3.0.5 on 2020-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20200407_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFormFields',
        ),
        migrations.AlterField(
            model_name='donation',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('revoked', 'Revoked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='amountstep',
            unique_together={('form', 'step')},
        ),
    ]
