# Generated by Django 3.0.8 on 2020-07-09 19:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20200709_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='donation_footer_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='personal_footer_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
