# Generated by Django 3.0.8 on 2020-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20200709_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='amount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('stepped', 'Fixed Steps'), ('custom', 'Custom Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='fixed_amount',
            field=models.FloatField(blank=True, help_text='Define fixed donation amount if you chose "Fixed Amount" for your Amount Type', null=True),
        ),
    ]
