# Generated by Django 3.0.5 on 2020-04-07 16:51

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20200407_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmeta',
            name='donation',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='donations.Donation'),
        ),
    ]
