# Generated by Django 3.0.5 on 2020-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20200407_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='recurring_status',
            field=models.CharField(choices=[('on-going', 'On-going'), ('cancelled', 'Cancelled'), ('non-recurring', 'Non-recurring')], default='non-recurring', max_length=255),
        ),
    ]
