# Generated by Django 3.0.8 on 2021-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_auto_20210217_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='object_id',
            new_name='profile_id',
        ),
    ]
