# Generated by Django 3.0.8 on 2021-02-23 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_auto_20210219_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribe_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 17, 47, 29, 153233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 17, 47, 29, 154301, tzinfo=utc)),
        ),
    ]
