# Generated by Django 3.0.8 on 2021-02-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_auto_20210219_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.DonationForm'),
        ),
    ]
