# Generated by Django 3.0.8 on 2021-03-31 15:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0026_auto_20210308_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test', models.BooleanField(default=False)),
                ('is_amount_custom', models.BooleanField(default=False)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=20)),
                ('guest_email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], max_length=255)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.DonationForm')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentGateway')),
            ],
            options={
                'verbose_name': 'Temp Donation',
                'verbose_name_plural': 'Temp Donations',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='guest_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='TempDonationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('donation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempMetas', to='donations.TempDonation')),
            ],
            options={
                'verbose_name': 'Temp Donation Meta',
                'verbose_name_plural': 'Temp Donation Metas',
                'ordering': ['-id'],
            },
        ),
    ]