# Generated by Django 3.1.11 on 2021-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0031_auto_20210517_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date', '-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-subscribe_date', '-created_at'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='donationmetafield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='default_frequency',
            field=models.CharField(choices=[('onetime', 'One-time'), ('monthly', 'Monthly')], default='onetime', max_length=20),
        ),
    ]
