# Generated by Django 3.0.14 on 2021-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0032_auto_20210521_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('usage', models.TextField()),
                ('email_subject', models.CharField(max_length=255)),
                ('email_text_body', models.TextField()),
                ('email_html_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['id'],
            },
        ),
    ]
