# Generated by Django 3.1.11 on 2021-05-24 08:28
import os
from django.db import migrations

from donations.email_template_ids import ET_ADN_ACCOUNT_CREATED, ET_ADN_ACCOUNT_DELETED, ET_ADN_DONATION_ERROR, ET_ADN_DONATION_REVOKED, ET_ADN_NEW_DONATION, ET_ADN_NEW_SUBSCRIPTION, ET_ADN_RENEWAL_DONATION, ET_ADN_SUBSCRIPTION_ADJUSTED, ET_ADN_SUBSCRIPTION_CANCELLED, ET_ADN_SUBSCRIPTION_CANCEL_REQUEST, ET_ADN_SUBSCRIPTION_PAUSED, ET_ADN_SUBSCRIPTION_RESCHEDULED, ET_ADN_SUBSCRIPTION_RESUMED, ET_DNR_ACCOUNT_DELETED, ET_DNR_DONATION_RECEIPT, ET_DNR_DONATION_REVOKED, ET_DNR_DONATION_STATUS_UPDATED, ET_DNR_NEW_SUBSCRIPTION, ET_DNR_RENEWAL_RECEIPT, ET_DNR_SUBSCRIPTION_ADJUSTED, ET_DNR_SUBSCRIPTION_CANCELLED, ET_DNR_SUBSCRIPTION_PAUSED, ET_DNR_SUBSCRIPTION_RESCHEDULED, ET_DNR_SUBSCRIPTION_RESUMED, ET_DNR_SUBSCRIPTION_STATUS_UPDATED
from newstream.settings.base import BASE_DIR
from donations.templates.donations.email_templates.plain_texts import default_account_created_admin_text, default_account_deleted_admin_text, default_account_deleted_donor_text, default_donation_receipt_text, default_donation_revoked_admin_text, default_donation_revoked_donor_text, default_donation_status_change_text, default_new_donation_text, default_new_renewal_text, default_recurring_cancel_request_admin_text, default_recurring_cancelled_admin_text, default_recurring_cancelled_donor_text, default_recurring_paused_admin_text, default_recurring_paused_donor_text, default_recurring_resumed_admin_text, default_recurring_resumed_donor_text, default_recurring_adjusted_admin_text, default_recurring_adjusted_donor_text, default_new_recurring_admin_text, default_new_recurring_donor_text, default_recurring_rescheduled_admin_text, default_recurring_rescheduled_donor_text, default_renewal_receipt_text, default_subscription_status_change_text, default_donation_error_admin_text

initial_data = [
    {
        "template_id": ET_DNR_DONATION_RECEIPT,
        "usage": "This is sent to the donor after an incoming webhook from a payment gateway confirms the completion of the transaction",
        "email_subject": "Thank You! This is your Donation Receipt.",
        "email_template_file": "donations/templates/donations/email_templates/donation_receipt.html",
        "text_func": default_donation_receipt_text
    },
    {
        "template_id": ET_DNR_DONATION_REVOKED,
        "usage": "This is sent to the donor after an incoming webhook from a payment gateway confirms the revoke of the transaction",
        "email_subject": "Your Donation is revoked.",
        "email_template_file": "donations/templates/donations/email_templates/donation_revoked_donor.html",
        "text_func": default_donation_revoked_donor_text
    },
    {
        "template_id": ET_DNR_DONATION_STATUS_UPDATED,
        "usage": "This is sent to the corresponding donor after admin manually updates a donation's payment status on wagtail",
        "email_subject": "Your Donation Payment Status has been updated.",
        "email_template_file": "donations/templates/donations/email_templates/donation_status_change.html",
        "text_func": default_donation_status_change_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_STATUS_UPDATED,
        "usage": "This is sent to the corresponding donor after admin manually updates a subscription's payment status on wagtail",
        "email_subject": "Your Recurring Donation Status has been updated.",
        "email_template_file": "donations/templates/donations/email_templates/subscription_status_change.html",
        "text_func": default_subscription_status_change_text
    },
    {
        "template_id": ET_DNR_RENEWAL_RECEIPT,
        "usage": "This is sent to the corresponding donor when an incoming webhook event from a payment gateway confirms the renewal charge of a subscription",
        "email_subject": "Thank You! This is your Renewal Donation Receipt.",
        "email_template_file": "donations/templates/donations/email_templates/renewal_receipt.html",
        "text_func": default_renewal_receipt_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_ADJUSTED,
        "usage": "This is sent to the donor after they have adjusted the amount of their subscription which is confirmed by an incoming webhook event",
        "email_subject": "Your Recurring Donation is Adjusted",
        "email_template_file": "donations/templates/donations/email_templates/recurring_adjusted_donor.html",
        "text_func": default_recurring_adjusted_donor_text
    },
    {
        "template_id": ET_DNR_NEW_SUBSCRIPTION,
        "usage": "This is sent to the donor after they have subscribed to a monthly donation which is confirmed by an incoming webhook event",
        "email_subject": "Your New Recurring Donation is Activated",
        "email_template_file": "donations/templates/donations/email_templates/recurring_activated.html",
        "text_func": default_new_recurring_donor_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_RESCHEDULED,
        "usage": "This is sent to the donor after they have rescheduled their subscription's billing date which is confirmed by an incoming webhook event",
        "email_subject": "Your Recurring Donation is Rescheduled",
        "email_template_file": "donations/templates/donations/email_templates/recurring_rescheduled_donor.html",
        "text_func": default_recurring_rescheduled_donor_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_PAUSED,
        "usage": "This is sent to the donor after they have paused their subscription",
        "email_subject": "Your Recurring Donation is paused",
        "email_template_file": "donations/templates/donations/email_templates/recurring_paused_donor.html",
        "text_func": default_recurring_paused_donor_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_RESUMED,
        "usage": "This is sent to the donor after they have resumed their subscription",
        "email_subject": "Your Recurring Donation is resumed",
        "email_template_file": "donations/templates/donations/email_templates/recurring_resumed_donor.html",
        "text_func": default_recurring_resumed_donor_text
    },
    {
        "template_id": ET_DNR_SUBSCRIPTION_CANCELLED,
        "usage": "This is sent to the donor after they have cancelled their subscription",
        "email_subject": "Your Recurring Donation is cancelled",
        "email_template_file": "donations/templates/donations/email_templates/recurring_cancelled_donor.html",
        "text_func": default_recurring_cancelled_donor_text
    },
    {
        "template_id": ET_DNR_ACCOUNT_DELETED,
        "usage": "This is sent to the donor after they have deleted their account",
        "email_subject": "Your Account is deleted",
        "email_template_file": "donations/templates/donations/email_templates/account_deleted_donor.html",
        "text_func": default_account_deleted_donor_text
    },
    {
        "template_id": ET_ADN_DONATION_ERROR,
        "usage": "This is sent to the admins after a donation error is raised",
        "email_subject": "A Donation Error has occurred",
        "email_template_file": "donations/templates/donations/email_templates/donation_error_admin.html",
        "text_func": default_donation_error_admin_text
    },
    {
        "template_id": ET_ADN_NEW_DONATION,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms that a new donation is successfully charged",
        "email_subject": "New Donation",
        "email_template_file": "donations/templates/donations/email_templates/new_donation.html",
        "text_func": default_new_donation_text
    },
    {
        "template_id": ET_ADN_DONATION_REVOKED,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms that a donation is revoked",
        "email_subject": "A Donation is revoked",
        "email_template_file": "donations/templates/donations/email_templates/donation_revoked_admin.html",
        "text_func": default_donation_revoked_admin_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_ADJUSTED,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms that the amount of a subscription has been adjusted",
        "email_subject": "A Recurring Donation is Adjusted",
        "email_template_file": "donations/templates/donations/email_templates/recurring_adjusted_admin.html",
        "text_func": default_recurring_adjusted_admin_text
    },
    {
        "template_id": ET_ADN_NEW_SUBSCRIPTION,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms that a new subscription has been made",
        "email_subject": "New Recurring Donation",
        "email_template_file": "donations/templates/donations/email_templates/new_recurring_donation.html",
        "text_func": default_new_recurring_admin_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_RESCHEDULED,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms that a subscription's billing date has been changed",
        "email_subject": "A Recurring Donation is Rescheduled",
        "email_template_file": "donations/templates/donations/email_templates/recurring_rescheduled_admin.html",
        "text_func": default_recurring_rescheduled_admin_text
    },
    {
        "template_id": ET_ADN_RENEWAL_DONATION,
        "usage": "This is sent to the admins when an incoming webhook event from a payment gateway confirms a renewal charge for a subscription",
        "email_subject": "New Renewal Donation",
        "email_template_file": "donations/templates/donations/email_templates/new_renewal.html",
        "text_func": default_new_renewal_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_PAUSED,
        "usage": "This is sent to the admins after a donor has paused their subscription",
        "email_subject": "A Recurring Donation is paused",
        "email_template_file": "donations/templates/donations/email_templates/recurring_paused_admin.html",
        "text_func": default_recurring_paused_admin_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_RESUMED,
        "usage": "This is sent to the admins after a donor has resumed their subscription",
        "email_subject": "A Recurring Donation is resumed",
        "email_template_file": "donations/templates/donations/email_templates/recurring_resumed_admin.html",
        "text_func": default_recurring_resumed_admin_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_CANCELLED,
        "usage": "This is sent to the admins after a donor has cancelled their subscription",
        "email_subject": "A Recurring Donation is cancelled",
        "email_template_file": "donations/templates/donations/email_templates/recurring_cancelled_admin.html",
        "text_func": default_recurring_cancelled_admin_text
    },
    {
        "template_id": ET_ADN_SUBSCRIPTION_CANCEL_REQUEST,
        "usage": "This is sent to the admins after a donor has requested to cancel their subscription",
        "email_subject": "Cancellation to a Recurring Donation is requested",
        "email_template_file": "donations/templates/donations/email_templates/recurring_cancel_request_admin.html",
        "text_func": default_recurring_cancel_request_admin_text
    },
    {
        "template_id": ET_ADN_ACCOUNT_CREATED,
        "usage": "This is sent to the admins after a donor first signs up for a monthly donation",
        "email_subject": "A Donor Account is created",
        "email_template_file": "donations/templates/donations/email_templates/account_created_admin.html",
        "text_func": default_account_created_admin_text
    },
    {
        "template_id": ET_ADN_ACCOUNT_DELETED,
        "usage": "This is sent to the admins after a donor have deleted their account",
        "email_subject": "A Donor Account is deleted",
        "email_template_file": "donations/templates/donations/email_templates/account_deleted_admin.html",
        "text_func": default_account_deleted_admin_text
    },
]


def load_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('donations', 'EmailTemplate')
    for template in initial_data:
        filepath = os.path.join(BASE_DIR, template["email_template_file"])
        templateFile = open(filepath, "r")
        et = EmailTemplate(
            template_id=template["template_id"],
            usage=template["usage"],
            email_subject=template["email_subject"],
            email_text_body=template["text_func"](),
            email_html_body=templateFile.read(),
        )
        et.save()
        templateFile.close()

def unload_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('donations', 'EmailTemplate')
    EmailTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0033_auto_20210521_0638'),
    ]

    operations = [
        migrations.RunPython(load_templates, unload_templates),
    ]
