# Generated by Django 3.1.11 on 2021-05-30 12:30
#
# Initial Data
#
# This sets up an initial DonationForm to make a usable site
# 

from django.db import migrations

def initial_data(apps, schema_editor):

    DonationForm = apps.get_model('donations', 'DonationForm')
    PaymentGateway = apps.get_model('site_settings', 'PaymentGateway')
    AmountStep = apps.get_model('donations', 'AmountStep')

    main_form = DonationForm.objects.create(
        title = "Main Form",
        description = "",
        default_frequency = "onetime",
        amount_type = "stepped_custom",
        fixed_amount = "250.00",
        donation_footer_text = "<p>By proceeding you are agreeing to our Terms and Conditions. You can cancel your donation at any time by logging in, or if you do not create an account, by emailing us directly at <a href=\"mailto:donations@hongkongfp.com\">donations@hongkongfp.com</a>.</p>",
        deleted = False,
    )

    gateways = PaymentGateway.objects.filter(
        frontend_label_attr_name__in = ['paypal_frontend_label', 'stripe_frontend_label', 'offline_frontend_label']
    )
    for gateway in gateways:
        main_form.allowed_gateways.add(gateway)
    
    step = AmountStep.objects.create(
        form = main_form,
        step = "100.00",
        default = False
    )

    step = AmountStep.objects.create(
        form = main_form,
        step = "200.00",
        default = False
    )


def remove_initial_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0035_auto_20210601_0712'),
        ('site_settings', '0002_auto_20200821_1058'),
    ]

    operations = [
         migrations.RunPython(initial_data, remove_initial_data),
    ]
