# Generated by Django 3.0.5 on 2020-04-21 11:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200421_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('full_width_image', wagtail.core.blocks.StructBlock([('banner', wagtail.images.blocks.ImageChooserBlock())])), ('raw_html', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
