# Generated by Django 3.0.5 on 2020-04-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings2c2p',
            options={'verbose_name': '2C2P Settings'},
        ),
        migrations.DeleteModel(
            name='TestSettings',
        ),
    ]
