# Generated by Django 3.0.8 on 2020-07-22 19:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_usermetafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='signup_footer_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
