# Generated by Django 3.0.8 on 2020-08-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200814_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='_2c2p_log_filename',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='_2c2p_testing_merchant_id',
            field=models.CharField(blank=True, help_text='Testing Merchant ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='_2c2p_testing_secret_key',
            field=models.CharField(blank=True, help_text='Testing Secret Key', max_length=255, null=True),
        ),
    ]
