# Generated by Django 3.0.8 on 2020-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_appearancesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminEmails',
        ),
    ]
