# Generated by Django 3.0.8 on 2020-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_testgeneralsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgeneralsettings',
            name='field_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testgeneralsettings',
            name='field_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testgeneralsettings',
            name='field_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testgeneralsettings',
            name='field_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
