# Generated by Django 3.0.8 on 2020-07-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_signup_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_auto_signup',
            field=models.BooleanField(default=False),
        ),
    ]
