# Generated by Django 3.0.8 on 2020-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_account_deleted_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_cancel_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_checkout_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_pause_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_renewal_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_resume_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_update_recurring_emails',
            field=models.BooleanField(default=True),
        ),
    ]
