# Generated by Django 3.0.8 on 2020-07-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_social_auto_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_auto_signup',
        ),
    ]
