# Generated by Django 3.0.8 on 2020-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_sitesettings_social_auto_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_skip_signup',
            field=models.BooleanField(default=False),
        ),
    ]
