# Generated by Django 3.0.8 on 2020-07-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_adminemails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='settings2c2p',
            name='site',
        ),
        migrations.DeleteModel(
            name='AppearanceSettings',
        ),
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.DeleteModel(
            name='Settings2C2P',
        ),
    ]
