# Generated by Django 3.0.8 on 2020-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20200921_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_account_created_emails',
            field=models.BooleanField(default=True),
        ),
    ]
