# Generated by Django 3.0.8 on 2020-09-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_remove_donationform_is_active'),
        ('site_settings', '0006_sitesettings_admin_receive_account_created_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donation_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='donations.DonationForm'),
        ),
    ]
