# Generated by Django 3.0.8 on 2020-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_social_skip_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_login_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
