# Generated by Django 3.0.8 on 2020-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_sitesettings_admin_receive_donation_error_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_api_product_id',
            field=models.CharField(blank=True, help_text='The Live API Product ID', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_sandbox_api_product_id',
            field=models.CharField(blank=True, help_text='The Sandbox API Product ID', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_testing_product_id',
            field=models.CharField(help_text='Testing Product ID accessible on your Stripe Dashboard', max_length=255, null=True),
        ),
    ]
