# Generated by Django 3.0.8 on 2020-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_auto_20201119_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='limit_fiveactions_per_fivemins',
            field=models.BooleanField(default=True, help_text='Enable this will limit donor to only 5 subscription update-actions every 5 minutes'),
        ),
    ]
