# Generated by Django 3.0.8 on 2021-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0017_auto_20210222_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='manual_frontend_label',
            field=models.CharField(default='Manual', help_text='The Gateway name to be shown on public-facing website for admin-added donations.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_frontend_label',
            field=models.CharField(default='Offline', help_text='The Gateway name to be shown on public-facing website for offline donations.', max_length=255),
        ),
    ]
