# Generated by Django 3.0.8 on 2021-02-22 22:22

from django.db import migrations

from site_settings.models import GATEWAY_PAYPAL_OLD

def populate_more_supported_gateways(apps, schema_editor):
    # We can't import the PaymentGateway model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PaymentGateway = apps.get_model('site_settings', 'PaymentGateway')

    supported_gateways = [
        {
            "title": GATEWAY_PAYPAL_OLD,
            "frontend_label_attr_name": "paypal_old_frontend_label",
            "list_order": 5
        },
    ]

    for gateway_args in supported_gateways:
        gateway = PaymentGateway(**gateway_args)
        gateway.save()

class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0019_sitesettings_paypal_old_frontend_label'),
    ]

    operations = [
        migrations.RunPython(populate_more_supported_gateways),
    ]