# Generated by Django 3.0.8 on 2021-02-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0021_auto_20210224_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label_en',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label_id_id',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label_ms',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label_tl',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label_zh_hant',
            field=models.CharField(default='PayPal', help_text='The Gateway name to be shown on public-facing website.', max_length=255, null=True),
        ),
    ]
