# Generated by Django 3.0.8 on 2021-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0023_sitesettings_privacy_policy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_testing_webhook_secret',
            field=models.CharField(blank=True, help_text='The Secret for the Testing Webhook used by the server for payment verification', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='The Secret for the Live Webhook used by the server for payment verification', max_length=255),
        ),
    ]