# Generated by Django 3.0.14 on 2021-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0025_usermetafield_clean_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='admin_receive_update_recurring_emails',
            new_name='admin_receive_adjusted_recurring_emails',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_new_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_rescheduled_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_revoked_emails',
            field=models.BooleanField(default=True),
        ),
    ]
