# Generated by Django 3.1.11 on 2021-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0026_auto_20210521_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_name',
            field=models.CharField(default='Newstream', max_length=255),
        ),
    ]
