# Generated by Django 3.1.11 on 2021-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0028_auto_20210601_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='admin_receive_update_recurring_emails',
            new_name='admin_receive_adjusted_recurring_emails',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_new_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_rescheduled_recurring_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_receive_revoked_emails',
            field=models.BooleanField(default=True),
        ),
    ]
