# Generated by Django 3.1.11 on 2021-06-08 11:05

from django.db import migrations
import i18nfield.fields
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0029_create_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='_2c2p_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_2c2p, help_text='The Gateway name to be shown on the frontend website.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='manual_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_manual, help_text='The Gateway name to be shown on the frontend website for admin-added donations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='offline_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_offline, help_text='The Gateway name to be shown on the frontend website for offline donations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_paypal, help_text='The Gateway name to be shown on public-facing website.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_legacy_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_paypal_legacy, help_text='The Gateway name to be shown on public-facing website for old Paypal transactions.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stripe_frontend_label',
            field=i18nfield.fields.I18nCharField(default=site_settings.models.get_i18n_label_stripe, help_text='The Gateway name to be shown on the frontend website.', max_length=255),
        ),
    ]
