# Generated by Django 3.0.8 on 2020-08-14 14:17

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0002_auto_20200814_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_id_id',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ms',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_tl',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_zh_hant',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text_id_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text_tl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_id_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_tl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
